channels:
  - UCW5OrUZ4SeUYkUg1XqcjFYA # GeoWizard
  - UCXuqSBlHAE6Xw-yeJA0Tunw # LinusTechTips
  - UCdBK94H6oZT2Q7l0-b0xmMg # ShortCircuit
  - UCbguawtJlHjxXzdAskubQVg # WilliamOsman2
  - UCWizIdwZdmr43zfxlCktmNw # AlecSteele
